version: '3.1'
services:
  w3champions-statistic-service-pr:
    image: modmoto/w3champions-statistic-service:#{TAG}#
    container_name: w3champions-statistic-service-pr-#{PR_NAME}#
    restart: always
    expose:
      - 80
    environment:
      - VIRTUAL_HOST=statistic-service-#{PR_NAME}#.pr.w3champions.com
      - LETSENCRYPT_HOST=statistic-service-#{PR_NAME}#.pr.w3champions.com
      - LETSENCRYPT_EMAIL=simonheiss87@gmail.com
      - MONGO_CONNECTION_STRING='mongodb://157.90.1.251:3513'
      - ADMIN_SECRET=#{ADMIN_SECRET}#
      - TAG=latest
      - START_HANDLERS=true
      - START_PAD_SYNC=false
      - MATCHMAKING_API=https://matchmaking-service.test.w3champions.com
      - IDENTIFICATION_SERVICE_URI=https://identification-service.test.w3champions.com
      - WAR3_INFO_API_KEY=#{WAR3_INFO_API_KEY}#

#  mongo-db:
#    image: mongo
#    container_name: mongo-db-w3c-statistics-pr-#{PR_NAME}#
#   restart: always
#   ports:
#     - 3510:27017
#   command: --wiredTigerCacheSizeGB=0.25
#    volumes:
#      - mongo-db-w3champions-statistics-pr-#{PR_NAME}#:/data/db

networks:
  default:
    external:
      name: nginx-proxy

#volumes:
#  mongo-db-w3champions-statistics-pr-#{PR_NAME}#:
